package webtheme

const TYPE_BREADCRUMBS = "breadcrumbs"
const TYPE_CODE = "code"
const TYPE_COLUMN = "column"
const TYPE_CONTAINER = "container"
const TYPE_DIV = "div"
const TYPE_HEADING = "heading"
const TYPE_HYPERLINK = "hyperlink"
const TYPE_ICON = "icon"
const TYPE_IMAGE = "image"
const TYPE_LIST_ITEM = "list_item"
const TYPE_ORDERED_LIST = "ordered_list"
const TYPE_RAW_HTML = "raw_html"
const TYPE_PARAGRAPH = "paragraph"
const TYPE_ROW = "row"
const TYPE_SECTION = "section"
const TYPE_TEXT = "text"
const TYPE_UNORDERED_LIST = "unordered_list"
